### ISSUE TITLE
Version number remains at 0.0.0

### ISSUE THREAD

**Issue by nolsto** [smartystreets/smartystreets-python-sdk#1]
In `__init__.py`,

`__version__ = '0.0.0'`

The latest release is version 1.0.2.

**Comment by MouaYing** [comment]
@nolsto , Are you looking at the code as it is in this repository, or the code as it exists in the tarball from PyPI? The version number for the code in this repository is intentionally kept at zero, but the PyPI tarball is supposed to have the current version there.

**Comment by nolsto** [comment]
@MouaYing Ah. I can see that the packaged version has the correct version set, yet I was referring to the code tagged in repo as 1.0.2, which I would've expected to have it set as well, since it's essentially frozen in its state.
