### ISSUE TITLE
'Lookup' object has no attribute 'input_id'

### ISSUE THREAD

**Issue by chadsaun** [smartystreets/smartystreets-python-sdk#12]
I just got this Exception when trying to run this code...

```
auth_id = settings.SMARTYSTREETS_ID
auth_token = settings.SMARTYSTREETS_TOKEN
credentials = StaticCredentials(auth_id, auth_token)
client = ClientBuilder(credentials).build_us_street_api_client()

lookup = Lookup(prefix=q)

client.send_lookup(lookup)
```

The `Lookup` class doesn't have any property named `input_id`

I'm using version 4.3.0 of the smartystreets_python_sdk

**Comment by DuncanBeutler** [comment]
It looks like you are trying to use a `prefix` property on the US Street API, the `Lookup` on this API doesn't have this property. Were you trying to use the US Autocomplete?

**Comment by DuncanBeutler** [comment]
Try making these changes:
`client = ClientBuilder(credentials).build_us_autocomplete_api_client()`
`lookup = Lookup(prefix='q')`

**Comment by chadsaun** [comment]
Yes, thanks. I was using the wrong client.
