### ISSUE TITLE
send_batch for international_street client

### ISSUE THREAD

**Issue by abelpenton** [smartystreets/smartystreets-python-sdk#17]
See this problem:
A have a list of merged address (US and international), and I need a method to validate all address of the list in an efficient way, if the list only have US addresses this was't be a problem because i can create a `Batch()` use the `send_batch` method in us-street client. The problem is when there are merge addresses on the list

Right now I solved the problem in a way that i don't really like, I made a batch with US addresses and used `send_batch` method of us_street client, and for international addresses on the list I sent it one by one. Is obvious this way is not the best. So... 

Maybe it's a good idea as long as it's possible to add the `send_batch` method to the international_street client as the us_street client does.

Or even better if there was a common client that receives a merged list of address of different countries and it be able to validate this addresses combining the `send_batch` methods in both clients

**Comment by mdwhatcott** [comment]
There are currently no plans to implement batching for the International Street API. The cost (and therefore the liabilities) are much higher for international lookups.
