### ISSUE TITLE
Handle seamlessly batch > 100 lookups

### ISSUE THREAD

**Issue by yiga2** [smartystreets/smartystreets-python-sdk#19]
Looking at the Client class of US street - and surely the same elsewhere -, there is no provision in the library to handle more than 100 lookups without some additional custom wrapper. User must deal with it and pass in chunks.

It would be useful if the SDK was handling this like so:
- send in chunks of 100
- accumulate in one single object all responses

I guess that's what the CLI is doing.

Thoughts ?

**Comment by mdwhatcott** [comment]
Yes, the [CLI](https://smartystreets.com/docs/plugins/smartylist/cli) reads a CSV file and processes multiple batches concurrently using the [Go SDK](https://github.com/smartystreets/smartystreets-go-sdk/).

The SDKs make it easy to communicate with the SmartyStreets APIs without needing to get into the details of HTTP. You are correct that we could modify them to be even more high-level and not impose batching limits, but we don't plan to do this. At some point with enough inputs the accumulation of responses would hit memory limits. The CLI flushes the responses to disk (the output csv file) to avoid this problem. Either you have to chunk up your batches (which does introduce complexity) or you have to stream responses to disk or to some other location so they don't build up in memory forever (a different kind of complexity).

**Comment by yiga2** [comment]
Thanks @mdwhatcott - we will probably implement our own API wrapper so we can use aiohttp and make back calls asynchronously. What is the maximum concurrent calls you accept ? 

Also to set the right expectations as we are only at design phase, what's the rough response time to expect for a 100 batch of US address resolution requests (from free text address) ?

**Comment by mdwhatcott** [comment]
There is currently no limit to the number of maximum connection per account (this could change in the future).  It is important for clients to implement some sort of retry strategy (w/ backoff) in response to [HTTP 429](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429). Our services are geo-distributed, load-balanced, and configured to auto-scale. We regularly handle **LARGE**, unanticipated spikes in traffic. Hit us with your best shot ;)

Round-trip response time for a single batch will depend greatly on the calling location. I suggest you run your own benchmarks from candidate locations to get an idea of the latency you can expect. You can see some of our own internal processing metrics (which exclude network latency) on our [status page](https://status.smartystreets.com/).
