### ISSUE TITLE
Some modules missing from packaged v1.0.2 on PyPI

### ISSUE THREAD

**Issue by nolsto** [smartystreets/smartystreets-python-sdk#2]
Importing the smartystreets_python_sdk throws an import error.

It appears as though the version 1.0.2 tarball accessible via PyPI is missing the `us_street` and `us_zipcode` modules.

**Comment by MouaYing** [comment]
Thank you for bringing this to our attention, @nolsto . We have added the missing modules, and they can be found in version 1.0.3.
