### ISSUE TITLE
Req: enhance freeform address parsing

### ISSUE THREAD

**Issue by yan-hic** [smartystreets/smartystreets-python-sdk#20]
Granted, not SDK related but couldn't figure out where to post enhancement requests - probably not even github.

**Use case**: 
We have many addresses that have the "ATTN:" element (and variations thereof), that is not relevant for geolocation. It should be ignored when validating.

Take the following address (as recorded in a database):
```
31390 Viking Pkwy
ATTN: Leonardo Caprio / Jon Slivan
Westlake OH 44145 
United States
```
The API _as of this writing_ does not like this and returns UNKNOWN/ADDRESS.
We could use a regex to parse and remove the ATTN line but ideally the API would do this (more efficiently).
Once the Attention portion is removed, API works as expected.

Let me know what channel can be best used to report API issues/enhancement requests.

**Comment by mdwhatcott** [comment]
@yiga2 - Have you tried using the US Extract API? The use case of that service is to extract and validate addresses from within larger bodies of freeform text. [In 'aggressive' mode it's pretty good at this sort of thing](https://smartystreets.com/products/apis/us-extract-api?auth-id=058ec44c-f9ca-cf23-f5d1-7807bc651ef4&auth-token=1pbm3s4VYz6mALOdvTNe&extract%20string=31390%20Viking%20Pkwy%20ATTN%3A%20Leonardo%20Caprio%20%2F%20Jon%20Slivan%20Westlake%20OH%2044145%20%20United%20States&aggressive=true&method=POST).

Here's an example of how to connect using this SDK: 

https://github.com/smartystreets/smartystreets-python-sdk/blob/master/examples/us_extract_example.py

(Here's now most of our customers get in touch with questions/feature requests: https://smartystreets.com/contact)/support

**Comment by yiga2** [comment]
@mdwhatcott US Extract API doesn't handle batch requests. I would just expect the US Street API to do a slightly better job in ignoring name or Attention elements, especially if these are passed as lines (separated by newline char). 1/3 of the addresses we pass fail so what we will likely do is cleanse the freeform ourselves first (one or 2 regexp), pass to US Street API and if that fails, to the US Extract API as fallback.

**Comment by mdwhatcott** [comment]
The US Extract API accepts up to 64k of raw text (per request) and attempts to extract any and all addresses from it, returning all validated addresses it finds. So, you actually can send it a batch of addresses, and depending on how your addresses are presented, you might actually get more than 100 within that 64k limit. Having said that I see what you're saying about improving the US Street API. We've got big plans in the works for improvements to the US Street API that are right up this alley. I'll forward your request to the team that's doing the dirty work on that project.

**Comment by yan-hic** [comment]
@RyanLCox1 can you expand on the close? This is quite old and I have moved on but some context would help.
