### ISSUE TITLE
Candidate missing input id

### ISSUE THREAD

**Issue by apgilfillan** [smartystreets/smartystreets-python-sdk#21]
I am using the python SDK for a Street lookup. When going through the successful results, the candidate returned is missing the input id given.

An when just looking at the lookup object itself and its input id, it doesn't seem to retain an input id when I set one.

 I am using the smartystreets-python-sdk 4.3.0

**Comment by mdwhatcott** [comment]
@apgilfillan - Can you provide a code snippet (w/ output) that consistently demonstrates the bug?

**Comment by apgilfillan** [comment]
Sorry for the inconvenience. This is my first time filing a bug. 

After some more thorough testing, I cannot seem to replicate the issue with the lookup object not retaining the input id.

But I am still seeing the candidate object missing the input id consistently

```
import InfraUtils
from smartystreets_python_sdk import StaticCredentials, exceptions, ClientBuilder
from smartystreets_python_sdk.us_street import Lookup as StreetLookup


credentials = InfraUtils.get_credentials('smarty_streets_api')

auth_id = credentials['username']
auth_token = credentials['password']


credentials = StaticCredentials(auth_id, auth_token)


client = ClientBuilder(credentials).build_us_street_api_client()


lookup = StreetLookup()

lookup.input_id = "1111"
lookup.street = "55 S Main St #351 Naperville IL 60540"
lookup.street2 = None
lookup.secondary = None
lookup.city = None
lookup.state = None
lookup.zipcode = None
lookup.lastline = None
lookup.addressee = None
lookup.urbanization = None
lookup.candidates = 1
lookup.match = "strict"
lookup.license = None

print(lookup.input_id)


try:
	client.send_lookup(lookup)
except exceptions.SmartyException as err:
	print(err)

print(lookup.input_id)

results = lookup.result

print(results[0].input_id)

```
Output:
```
Before Lookup: 1111
After Lookup: 1111
Traceback (most recent call last):
  File "/dids/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-35-cfdd469bfcef>", line 69, in <module>
    print(results[0].input_id)
AttributeError: 'Candidate' object has no attribute 'input_id'
```
Picture of the results object
![image](https://user-images.githubusercontent.com/20178198/97206225-71f6fa80-1786-11eb-9447-a1d49105dcd7.png)

Hopefully, this helps. If you need more examples or the candidate object is not suppose to contain an input_id, sorry for all the trouble.

**Comment by mdwhatcott** [comment]
@apgilfillan - It appears that this issue [was fixed](https://github.com/smartystreets/smartystreets-python-sdk/commit/0ff72f01fa691925167de031341d87819aeec6dc) after the release of `4.3.0`. Please download a later version and retry.

**Comment by apgilfillan** [comment]
Thanks so much. Upgrading to a newer version fixed the issue.
