### ISSUE TITLE
Latest release, 4.7.0, is broken

### ISSUE THREAD

**Issue by tsibley** [smartystreets/smartystreets-python-sdk#23]
The latest release, version 4.7.0, appears to be broken because of a packaging/distribution error. The new `smartystreets_python_sdk.us_reverse_geo` package is missing from `setup.py`:

https://github.com/smartystreets/smartystreets-python-sdk/blob/72c375afcc88a4fe8560ac4b45e9a1957583c3b0/setup.py#L11-L19

and thus doesn't get installed. ModuleNotFoundErrors occur when trying to use the ClientBuilder, which imports `us_reverse_geo`:

```
Traceback (most recent call last):
  …
  File "…", line 32, in <module>
    from smartystreets_python_sdk import StaticCredentials, ClientBuilder
  File "…/lib/python3.6/site-packages/smartystreets_python_sdk/__init__.py", line 13, in <module>
    from .client_builder import ClientBuilder
  File "…/lib/python3.6/site-packages/smartystreets_python_sdk/client_builder.py", line 6, in <module>
    from smartystreets_python_sdk.us_reverse_geo import Client as USReverseGeoClient
ModuleNotFoundError: No module named 'smartystreets_python_sdk.us_reverse_geo'
```

**Comment by tsibley** [comment]
Reproduction:

```
$ python3 -m venv /tmp/venv
$ /tmp/venv/bin/pip install smartystreets-python-sdk==4.7.0
$ /tmp/venv/bin/python3 -c 'from smartystreets_python_sdk import ClientBuilder'
```

**Comment by DuncanBeutler** [comment]
Thanks for raising this issue. Changes have been made to the setup file on version 4.7.1, let us know if there are persisting issues

**Comment by tsibley** [comment]
This appears resolved, thanks!
