### ISSUE TITLE
Latest release, 4.8.0, is broken

### ISSUE THREAD

**Issue by tsibley** [smartystreets/smartystreets-python-sdk#30]
The latest release, version 4.8.0, appears to be broken because of a packaging/distribution error. The new `smartystreets_python_sdk.us_autocomplete_pro` package is missing from `setup.py`:

https://github.com/smartystreets/smartystreets-python-sdk/blob/a811bec4f4c7b507ac693c60cab63c04ceced159/setup.py#L11-L20

and thus doesn't get installed. ModuleNotFoundErrors occur when trying to use the ClientBuilder, which imports `us_autocomplete_pro`:

```
Traceback (most recent call last):
  …
  File "…", line 32, in <module>
    from smartystreets_python_sdk import StaticCredentials, ClientBuilder
  File "…/lib/python3.6/site-packages/smartystreets_python_sdk/__init__.py", line 13, in <module>
    from .client_builder import ClientBuilder
  File "…/lib/python3.6/site-packages/smartystreets_python_sdk/client_builder.py", line 6, in <module>
    from smartystreets_python_sdk.us_autocomplete_pro import Client as USAutocompleteProClient
ModuleNotFoundError: No module named 'smartystreets_python_sdk.us_autocomplete_pro'
```

A [similar issue](https://github.com/smartystreets/smartystreets-python-sdk/issues/23) with a different new module occurred with the 4.7.0 release last year.

**Comment by mdwhatcott** [comment]
Fixed by PR #31
