### ISSUE TITLE
 max_timeout in ClientBuilder seems to be in seconds and not in milliseconds

### ISSUE THREAD

**Issue by lfreeman** [smartystreets/smartystreets-python-sdk#37]
max_timeout in ClientBuilder seems to be in seconds and not in milliseconds as specified in the docstring of with_max_timeout

https://github.com/smartystreets/smartystreets-python-sdk/blob/7d09f38421e6ad73a2862b412762226bf4c7d28f/smartystreets_python_sdk/client_builder.py#L49

**Comment by RyanLCox1** [comment]
This has been changed to reflect that the value is in seconds, not milliseconds. Thank you for pointing it out!
