### ISSUE TITLE
RequestsSender creates a Session, but doesn't close it if there is an exception

### ISSUE THREAD

**Issue by rgegriff** [smartystreets/smartystreets-python-sdk#38]
The RequestsSender class will create a requests Session object, but if there is an exception, there is a risk that the session never gets closed, keeping the TCP connection open.

We ran into this and it ended up eventually exhausting our nofile ulimit after enough errors.

**Comment by RyanLCox1** [comment]
I think I have this handled now. It's fixed in 4.11.11
