### ISSUE TITLE
ClientBuilder(credentials).with_proxy() no longer works 

### ISSUE THREAD

**Issue by berrym-hln** [smartystreets/smartystreets-python-sdk#41]
In the examples, using the client with a proxy, like this:

`client = ClientBuilder(credentials).with_proxy('localhost:8080', 'user', 'password').build_us_street_api_client()`

Worked fine with requests 2.18.4 and urllib3 1.22, but no longer works with the latest versions of requests (2.27.1) and urllib3 (1.26.16). Something about the API for proxy connections must have changed between these versions and will need to be updated in Smarty's ClientBuilder code. Thanks!

**Comment by RyanLCox1** [comment]
This is now fixed with the release of 4.14.4
