### ISSUE TITLE
No custom headers for client builder in the Python SDK

### ISSUE THREAD

**Issue by Capsman08** [smartystreets/smartystreets-python-sdk#9]
In the other language client builder SDKs there is the option for custom headers to be sent through for use in proxies or whatever (example [Java](https://github.com/smartystreets/smartystreets-java-sdk/blob/master/src/main/java/com/smartystreets/api/ClientBuilder.java#L20) ). The python SDK does not have this functionality.

I spoke to Jeffrey Duncan about this as well for reference.

**Comment by MouaYing** [comment]
Thank you for your input! This feature had indeed not yet been added to the Python SDK. Fret not, but rejoice! For it has just been added, and is part of the very latest release (version 4.3.0).
